package azure

var AZUREEndpoints = map[string]string{
	"centralus":          "https://astcentralus.blob.core.windows.net/public/callback.js",
	"eastus2":            "https://asteastus2.blob.core.windows.net/public/callback.js",
	"eastus":             "https://asteastus.blob.core.windows.net/public/callback.js",
	"northcentralus":     "https://astnorthcentralus.blob.core.windows.net/public/callback.js",
	"southcentralus":     "https://astsouthcentralus.blob.core.windows.net/public/callback.js",
	"westus2":            "https://astwestus2.blob.core.windows.net/public/callback.js",
	"westcentralus":      "https://astwestcentralus.blob.core.windows.net/public/callback.js",
	"westus":             "https://astwestus.blob.core.windows.net/public/callback.js",
	"canadacentral":      "https://astcanadacentral.blob.core.windows.net/public/callback.js",
	"canadaeast":         "https://astcanadaeast.blob.core.windows.net/public/callback.js",
	"brazilsouth":        "https://astbrazilsouth.blob.core.windows.net/public/callback.js",
	"northeurope":        "https://astnortheurope.blob.core.windows.net/public/callback.js",
	"westeurope":         "https://astwesteurope.blob.core.windows.net/public/callback.js",
	"francecentral":      "https://astfrancecentral.blob.core.windows.net/public/callback.js",
	"uksouth":            "https://astuksouth.blob.core.windows.net/public/callback.js",
	"ukwest":             "https://astukwest.blob.core.windows.net/public/callback.js",
	"eastasia":           "https://asteastasia.blob.core.windows.net/public/callback.js",
	"southeastasia":      "https://astsoutheastasia.blob.core.windows.net/public/callback.js",
	"australiaeast":      "https://astaustraliaeast.blob.core.windows.net/public/callback.js",
	"australiasoutheast": "https://astaustraliasoutheast.blob.core.windows.net/public/callback.js",
	"centralindia":       "https://astcentralindia.blob.core.windows.net/public/callback.js",
	"southindia":         "https://astsouthindia.blob.core.windows.net/public/callback.js",
	"westindia":          "https://astwestindia.blob.core.windows.net/public/callback.js",
	"japaneast":          "https://astjapaneast.blob.core.windows.net/public/callback.js",
	"japanwest":          "https://astjapanwest.blob.core.windows.net/public/callback.js",
	"koreacentral":       "https://astkoreacentral.blob.core.windows.net/public/callback.js",
	"koreasouth":         "https://astkoreasouth.blob.core.windows.net/public/callback.js",
	"southafricanorth":   "https://astsouthafricanorth.blob.core.windows.net/public/callback.js",
}

var AZURERegions = map[string]string{
	"centralus":          "United States (Central US)",
	"eastus2":            "United States (East US 2)",
	"eastus":             "United States (East US)",
	"northcentralus":     "United States (North Central US)",
	"southcentralus":     "United States (South Central US)",
	"westus2":            "United States (West US 2)",
	"westcentralus":      "United States (West Central US)",
	"westus":             "United States (West US)",
	"canadacentral":      "Canada (Canada Central)",
	"canadaeast":         "Canada (Canada East)",
	"brazilsouth":        "Brazil (Brazil South)",
	"northeurope":        "Europe (North Europe)",
	"westeurope":         "Europe (West Europe)",
	"francecentral":      "France (France Central)",
	"uksouth":            "United Kingdom (UK South)",
	"ukwest":             "United Kingdom (UK West)",
	"eastasia":           "Asia Pacific (East Asia)",
	"southeastasia":      "Asia Pacific (Southeast Asia)",
	"australiaeast":      "Australia (Australia East)",
	"australiasoutheast": "Australia (Australia Southeast)",
	"centralindia":       "India (Central India)",
	"southindia":         "India (South India)",
	"westindia":          "India (West India)",
	"japaneast":          "Japan (Japan East)",
	"japanwest":          "Japan (Japan West)",
	"koreacentral":       "Korea (Korea Central)",
	"koreasouth":         "Korea (Korea South)",
	"southafricanorth":   "Africa (South Africa North)",
}
