package azure

var AZUREEndpoints = map[string]string{
	"centralus":          "http://astcentralus.blob.core.windows.net/public/callback.js",
	"eastus2":            "http://asteastus2.blob.core.windows.net/public/callback.js",
	"eastus":             "http://asteastus.blob.core.windows.net/public/callback.js",
	"northcentralus":     "http://astnorthcentralus.blob.core.windows.net/public/callback.js",
	"southcentralus":     "http://astsouthcentralus.blob.core.windows.net/public/callback.js",
	"westus2":            "http://astwestus2.blob.core.windows.net/public/callback.js",
	"westcentralus":      "http://astwestcentralus.blob.core.windows.net/public/callback.js",
	"westus":             "http://astwestus.blob.core.windows.net/public/callback.js",
	"canadacentral":      "http://astcanadacentral.blob.core.windows.net/public/callback.js",
	"canadaeast":         "http://astcanadaeast.blob.core.windows.net/public/callback.js",
	"brazilsouth":        "http://astbrazilsouth.blob.core.windows.net/public/callback.js",
	"northeurope":        "http://astnortheurope.blob.core.windows.net/public/callback.js",
	"westeurope":         "http://astwesteurope.blob.core.windows.net/public/callback.js",
	"francecentral":      "http://astfrancecentral.blob.core.windows.net/public/callback.js",
	"uksouth":            "http://astuksouth.blob.core.windows.net/public/callback.js",
	"ukwest":             "http://astukwest.blob.core.windows.net/public/callback.js",
	"eastasia":           "http://asteastasia.blob.core.windows.net/public/callback.js",
	"southeastasia":      "http://astsoutheastasia.blob.core.windows.net/public/callback.js",
	"australiaeast":      "http://astaustraliaeast.blob.core.windows.net/public/callback.js",
	"australiasoutheast": "http://astaustraliasoutheast.blob.core.windows.net/public/callback.js",
	"centralindia":       "http://astcentralindia.blob.core.windows.net/public/callback.js",
	"southindia":         "http://astsouthindia.blob.core.windows.net/public/callback.js",
	"westindia":          "http://astwestindia.blob.core.windows.net/public/callback.js",
	"japaneast":          "http://astjapaneast.blob.core.windows.net/public/callback.js",
	"japanwest":          "http://astjapanwest.blob.core.windows.net/public/callback.js",
	"koreacentral":       "http://astkoreacentral.blob.core.windows.net/public/callback.js",
	"koreasouth":         "http://astkoreasouth.blob.core.windows.net/public/callback.js",
	"southafricanorth":   "http://astsouthafricanorth.blob.core.windows.net/public/callback.js",
}

var AZURERegions = map[string]string{
	"centralus":          "United States (Central US)",
	"eastus2":            "United States (East US 2)",
	"eastus":             "United States (East US)",
	"northcentralus":     "United States (North Central US)",
	"southcentralus":     "United States (South Central US)",
	"westus2":            "United States (West US 2)",
	"westcentralus":      "United States (West Central US)",
	"westus":             "United States (West US)",
	"canadacentral":      "Canada (Canada Central)",
	"canadaeast":         "Canada (Canada East)",
	"brazilsouth":        "Brazil (Brazil South)",
	"northeurope":        "Europe (North Europe)",
	"westeurope":         "Europe (West Europe)",
	"francecentral":      "France (France Central)",
	"uksouth":            "United Kingdom (UK South)",
	"ukwest":             "United Kingdom (UK West)",
	"eastasia":           "Asia Pacific (East Asia)",
	"southeastasia":      "Asia Pacific (Southeast Asia)",
	"australiaeast":      "Australia (Australia East)",
	"australiasoutheast": "Australia (Australia Southeast)",
	"centralindia":       "India (Central India)",
	"southindia":         "India (South India)",
	"westindia":          "India (West India)",
	"japaneast":          "Japan (Japan East)",
	"japanwest":          "Japan (Japan West)",
	"koreacentral":       "Korea (Korea Central)",
	"koreasouth":         "Korea (Korea South)",
	"southafricanorth":   "Africa (South Africa North)",
}
